language: ruby

services:
    - mysql
    # - postgresql

rvm:
    - 2.1.8
    # - 2.2.4
    # - 2.3.0
    # - jruby

gemfile:
    - $REDMINE_PATH/Gemfile

env:
    - REDMINE_VER=3.0.7 DB=mysql
    # - REDMINE_VER=3.1.3 DB=mysql
    # - REDMINE_VER=3.2.0 DB=mysql
    # - REDMINE_VER=3.0.7 DB=postgresql
    # - REDMINE_VER=3.1.3 DB=postgresql
    # - REDMINE_VER=3.2.0 DB=postgresql

before_install:
    - export PLUGIN_NAME=redmine_tags
    - export REDMINE_PATH=$HOME/redmine
    - git clone https://github.com/redmine/redmine.git --branch $REDMINE_VER --depth 1 $REDMINE_PATH
    - git clone https://github.com/ZitecCOM/redmine_testing_gems.git --branch feature/testem-integration --depth 1 $REDMINE_PATH/plugins/redmine_testing_gems
    - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
    - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
    - cd $REDMINE_PATH
    - echo "gem 'rake', '< 11.0'" >> Gemfile
    - cd plugins/redmine_testing_gems
    - make install.all

before_script:
    - bundle exec rake db:create db:migrate redmine:plugins:migrate RAILS_ENV=test

script:
    - bundle exec rake redmine:plugins:spec RAILS_ENV=test NAME=$PLUGIN_NAME
    - echo `pwd`
    - testem ci -R dot --file plugins/redmine_tags/testem.js
