language: ruby

services:
  - mysql
  # - postgresql

rvm:
  - 2.1.8
  # - 2.2.4
  # - 2.3.0
  # - jruby

node_js:
  - '5.8'

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=3.0.7 DB=mysql
  # - REDMINE_VER=3.1.3 DB=mysql
  # - REDMINE_VER=3.2.0 DB=mysql
  # - REDMINE_VER=3.0.7 DB=postgresql
  # - REDMINE_VER=3.1.3 DB=postgresql
  # - REDMINE_VER=3.2.0 DB=postgresql

before_install:
  - export PLUGIN_NAME=redmine_tags
  - export REDMINE_PATH=$HOME/redmine
  - git clone https://github.com/redmine/redmine.git --branch $REDMINE_VER --depth 1 $REDMINE_PATH
  - git clone https://github.com/ZitecCOM/redmine_testing_gems.git --branch feature/testem-integration --depth 1 $REDMINE_PATH/plugins/redmine_testing_gems
  - cp -R $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - echo "gem 'rake', '< 11.0'" >> $REDMINE_PATH/Gemfile
  - cd $REDMINE_PATH/plugins/redmine_testing_gems
  - nvm install 5.8.0
  - make install.all
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create db:migrate redmine:plugins:migrate RAILS_ENV=test

script:
  - bundle exec rake redmine:plugins:spec RAILS_ENV=test NAME=$PLUGIN_NAME
  - testem ci --launch PhantomJS --file plugins/redmine_tags/testem.js
